# Generated by Django 5.2.13 on 2026-05-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("ETF", "ETF"),
                            ("STOCK", "Hisse"),
                            ("FUND", "Fon"),
                            ("GOLD", "Altın"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("avg_cost", models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                "ordering": ["asset_type", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="MorningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("full_analysis", models.JSONField(default=dict)),
                (
                    "total_portfolio_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price_eur", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("asset", "date")},
            },
        ),
    ]
